In [1]:
import pandas as pd

In [2]:
fr=pd.read_csv('pop_age15plus_sex_socioprof.CSV', sep=';')

C:\Users\edebo\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
fr

,NIVGEO,CODGEO,LIBGEO,CS1_8,AGEQ65,SEXE,NB
0,ARM,13201,Marseille 1er Arrondissement,1,15,1,0.000000
1,ARM,13201,Marseille 1er Arrondissement,1,15,2,0.000000
2,ARM,13201,Marseille 1er Arrondissement,1,20,1,0.000000
3,ARM,13201,Marseille 1er Arrondissement,1,20,2,0.000000
4,ARM,13201,Marseille 1er Arrondissement,1,25,1,0.000000
...,...,...,...,...,...,...,...
6158763,COM,97424,Cilaos,8,55,2,45.551263
6158764,COM,97424,Cilaos,8,60,1,30.882284
6158765,COM,97424,Cilaos,8,60,2,61.032835
6158766,COM,97424,Cilaos,8,65,1,10.343150
6158767,COM,97424,Cilaos,8,65,2,40.931041

In [11]:
fr.to_excel('pop_age15plus_sex_socioprof.xlsx')

ValueError: This sheet is too large! Your sheet size is: 6158768, 7 Max sheet size is: 1048576, 16384